# Generated by Django 5.0.2 on 2024-03-05 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_cg', models.IntegerField(primary_key=True, serialize=False)),
                ('name_cg', models.CharField(max_length=255)),
                ('hourly_wage_cg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id_w', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name_w', models.CharField(max_length=255)),
                ('address_w', models.CharField(max_length=255)),
                ('phone_w', models.CharField(max_length=255)),
                ('email_w', models.CharField(max_length=255)),
                ('department_w', models.CharField(max_length=255)),
                ('num_account_w', models.CharField(max_length=16)),
                ('fk_id_cg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceta.category')),
            ],
        ),
    ]
