# Generated by Django 5.0.2 on 2024-03-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id_cg',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
