# Generated by Django 5.0.2 on 2024-03-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceta', '0003_client_role_contract_paymentterm_expense_bill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='manager_serv',
        ),
        migrations.RemoveField(
            model_name='service',
            name='workers_count',
        ),
    ]
